
class locators:
    URL = "https://www.flipkart.com/"
    Invalidlogin="//body/div[2]/div/div/div/div/div[2]/div/form/div[1]/span[2]/span"
    phone = "//body/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/form[1]/div[1]/input[1]"
    Password = "//body/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/form[1]/div[2]/input[1]"
    Login = "//body/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/form[1]/div[4]/button[1]"
    Flipkart = "//body/div[@id='container']/div[1]/div[1]/div[1]/div[2]/div[3]/div[1]/div[1]/div[1]/div[1]"
    Grocery="//div[text()='Grocery']"
    Grocerypage="//body/div[@id='container']/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/a[1]/img[1]"
    Search="//input[@title='Search for products, brands and more']"
    Searchsubmit="//button[@class='L0Z3Pu']"

    laptop="//body[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/a[1]/div[2]/div[1]/div[1]"
    producttext="//*[@id='container']/div/div[3]/div[1]/div[2]/div[2]/div/div[1]/h1/span"
    Kitchenstove="//*[@id='container']/div/div[3]/div[1]/div[2]/div[2]/div/div[1]/div/a[2]"
    Football="//body/div[@id='container']/div[1]/div[3]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/a[2]"
    Addcart="//*[@id='container']/div/div[3]/div[1]/div[1]/div[2]/div/ul/li[1]/button"
    Cart="//body/div[@id='container']/div[1]/div[1]/div[1]/div[2]/div[6]/div[1]/div[1]"
    addcart="//a[@class='_2Kn22P gBNbID']"
    #Stoveaddcart="//*[@id='container']/div/div[2]/div/div/div[1]/div/div[2]/div/div[1]/div[1]/div[1]/a"
    price="//*[@id='container']/div/div[3]/div[1]/div[2]/div[2]/div/div[1]/div/a[3]/div[1]/div[1]"
    pricelaptop="//*[@id='container']/div/div[3]/div[1]/div[2]/div[2]/div/div/div/a/div[2]/div[2]/div[1]/div[1]/div[1]"
    #footballcart="//*[@id='container']/div/div[2]/div/div[1]/div[1]/div/div[2]/div/div[1]/div[1]/div[1]/a"
    Cartprice="//span[@class='_2-ut7f _1WpvJ7']"

    #Cartpricestove="//*[@id='container']/div/div[2]/div/div/div[1]/div/div[2]/div/div[1]/div[1]/span[2]"
    #Cartpricefootball="//*[@id='container']/div/div[2]/div/div[1]/div[1]/div/div[2]/div/div[1]/div[1]/span[2]"

    Branditemslist="//div[@class='QvtND5 _2w_U27']/span"
    Brand="//div[@class='_38vbm7']"
    Applyfilters="//span[text()='Apply Filters']"
    productfiltered="//*[@id='container']/div/div[3]/div/div[2]/div[2]/div/div/div/a[2]"

    Fashion="//div[text()='Fashion']"
    #drop="//*[@id='container']/div/div[2]/div/div/div[4]/a/div[2]/div[2]/div[2]"
    section1="//*[@id='container']/div/div[2]/div/div/div[4]/a/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/a[1]"
    section2="//*[@id='container']/div/div[2]/div/div/div[4]/a/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/a[3]"
#"//*[@id="container"]/div/div[2]/div/div/div[4]/a/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/a[1]"
    addproductwishlist="//div[@class='_36FSn5']"

    product="(//a[@class='IRpwTa'])[1]"
    product1text="//span[@class='B_NuCI']"
    Wishlist="//*[@id='container']/div/div[1]/div[1]/div[2]/div[3]/div/div/div[2]/div[2]/div/ul/li[5]/a/div"
    Wishlistproduct1="//div[@class='_3hscEA'][1]"


    Profile="//*[@id='container']/div/div[1]/div[1]/div[2]/div[3]/div/div/div[2]/div[2]/div/ul/li[1]/a/div"
    Addaddress="//*[@id='container']/div/div[3]/div/div[2]/div/div/div/div[1]/div/div"
    Manageaddress="//div[text()='Manage Addresses']"
    Name="//input[@name='name']"
    mobile="//input[@name='phone']"
    Negativephone="//span[text()='Not a valid phone number.']"
    pincode="//input[@name='pincode']"
    Negativepincode="//span[text()='Not a valid pincode']"
    locality="//input[@name='addressLine2']"
    addresss="//textarea[@name='addressLine1']"
    city="//input[@name='city']"
    state="//select[@name='state']"
    landmark="//input[@name='landmark']"
    alternatphone="//input[@name='alternatePhone']"
    Home="//*[@id='container']/div/div[3]/div/div[2]/div/div/div/div[1]/div/div/form/div/div[7]/div/div/label[1]/div[1]"
    save="//button[text()='Save']"
    SavedName="//div[@class='_1CeZIA']/div/p/span[1]"
    SavedPhonenumber="//span[@class='_1Z7fmh _3CfVDh']"

    Logout="//span[text()='Logout']"
    login="//span[text()='Login']"
